### ISSUE TITLE
no auth method defined

### ISSUE THREAD

**Issue by jandrieu** [ruimarinho/bitcoin-core#29]
When trying to get a balance, I get the error "no auth method defined".

I didn't set up a username/passwd with the bitcoin core. What should i be doing here?

**Comment by tloriato** [comment]
Did you manage to resolve that issue @jandrieu ?

**Comment by Ollemesh** [comment]
You have to set it:
Open or create your _bitcoin.conf_ file (path for linux: _~/.bitcoin/.bitcoin.conf_ ), and write there:
`
rpcuser=user
rpcpassword=pass
`,
after that make necessary changes is the bitcoin-core module options: 
`
const Bitcoin = require('bitcion-core')
const bitcoin = new Bitcoin({
    username: 'user',
    password: 'pass',
    /* other options */
})
`

**Comment by pedrobranco** [comment]
For increasing the security in the configuration file, instead of using `rpcuser` or `rpcpassword` use `rpcauth`. 

Check `rpcauth` help [here](https://en.bitcoin.it/wiki/Running_Bitcoin). To generate an encrypted version of the password you can use this [script](https://github.com/bitcoin/bitcoin/tree/master/share/rpcuser).

**Comment by wmitsuda** [comment]
bitcoin-cli works fine without setting a user/password and is the default configuration of bitcoind. I think this client should support running with no user/pass.

**Comment by pedrobranco** [comment]
Works fine without setting a user/password because it uses the same `bitcoind.conf`.

[Check the source here](https://bitcoin.org/en/developer-examples).
> All three programs get settings from bitcoin.conf in the Bitcoin application directory

> To use bitcoind and bitcoin-cli, you will need to add a RPC password to your bitcoin.conf file. Both programs will read from the same file if both run on the same system as the same user, so any long random password will work

**Comment by wmitsuda** [comment]
@pedrobranco currently I'm using a bitcoin.conf with no rpc user/pass at ~/Library/Application Support/Bitcoin/ on macos, and it is working fine.

Can you confirm if the user/pass is required in your environment?

**Comment by jandrieu** [comment]
FWIW, @Ollemesh's suggestion worked. Out of the box, however, the module did not. Maybe it would have on Linux, but I was on Windows.

**Comment by larafale** [comment]
I'm on osx, using bitcoin core 0.15.0.1, `bitcoin-cli` by default work out of the box without password. but for this module, having no password set in `bitcoin.conf` result in the `no auth method defined` error. which can be a pain because now I have to specify auth creds for `bitcoin-cli` to work.

**Comment by ruimarinho** [comment]
It works because it's using the cookie based authentication system which [requires local file access](https://github.com/bitcoin/bitcoin/blob/c9a4aa8a0e7e0e22f2d8bbf88f58eb749ad83a25/src/rpc/protocol.cpp#L113-L127). Figuring out the data location is not a trivial process. It works fine on bitcoin-cli because it runs the `GetDataDir()` function [provided by Qt](http://doc.qt.io/qt-5/qstandardpaths.html). On node, we would have to figure out not only the standard path but also its possible modification (via -datadir argument) by reading the bitcoin.conf file (whose location can also be changed).

In addition to all of this, it would also require setting up dedicated machines for Windows and Linux on Travis instead of just using Docker.

If you have any other suggestion, feel free to add a comment. Be sure to take a look at the [Docker version instructions for easier testing](https://github.com/ruimarinho/docker-bitcoin-core#using-rpcauth-for-remote-authentication).
